sudo: required

services:
  - docker

before_install:
  - docker build -t test .

script:
  # describe: tools exist
  - docker run --rm -v $PWD:/data test /bin/bash -c "which wget wput curl zip tar rsync make"
  # describe: should render latex
  # * biblatex biber
  # * math
  # * utf8 chars
  - docker run --rm -v $PWD:/data test /bin/bash -c "cd test && pdflatex test && biber test && pdflatex test && pdflatex test"
  # describe: should render markdown to pdf
  # * math
  # * utf8 chars
  - docker run --rm -v $PWD:/data test /bin/bash -c "pandoc --toc test/test.md -o test.pdf"
